default: &default
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
    <<: *default
    database: insta_app_development
test:
    <<: *default
    database: insta_app_test
production:
    primary: &primary_production
        <<: *default
        database: insta_app_production
        username: insta_app
        password: <%= ENV["INSTA_APP_DATABASE_PASSWORD"] %>
    cache:
        <<: *primary_production
        database: insta_app_production_cache
        migrations_paths: db/cache_migrate
    queue:
        <<: *primary_production
        database: insta_app_production_queue
        migrations_paths: db/queue_migrate
    cable:
        <<: *primary_production
        database: insta_app_production_cable
        migrations_paths: db/cable_migrate
